/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 51
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  aux_sym__object_body_token1 = 3,
  anon_sym_COLON = 4,
  anon_sym_EQ = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  sym_identifier = 8,
  anon_sym_SQUOTE = 9,
  anon_sym_DQUOTE = 10,
  sym_double_string_content = 11,
  sym_single_string_content = 12,
  sym_escape_sequence = 13,
  anon_sym_DASH = 14,
  anon_sym_PLUS = 15,
  anon_sym_Infinity = 16,
  anon_sym_NaN = 17,
  sym__number = 18,
  sym__hexadecimal_number = 19,
  sym_true = 20,
  sym_false = 21,
  sym_null = 22,
  sym_comment = 23,
  sym_document = 24,
  sym__value = 25,
  sym_object = 26,
  sym__object_body = 27,
  sym_pair = 28,
  sym_array = 29,
  sym_string = 30,
  sym__single_quoted_string = 31,
  sym__double_quoted_string = 32,
  aux_sym__single_string_content = 33,
  aux_sym__double_string_content = 34,
  sym__sign = 35,
  sym_number = 36,
  aux_sym__object_body_repeat1 = 37,
  aux_sym_array_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym__object_body_token1] = "_object_body_token1",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_identifier] = "identifier",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym_double_string_content] = "string_content",
  [sym_single_string_content] = "string_content",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_Infinity] = "Infinity",
  [anon_sym_NaN] = "NaN",
  [sym__number] = "_number",
  [sym__hexadecimal_number] = "_hexadecimal_number",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_null] = "null",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym__value] = "_value",
  [sym_object] = "object",
  [sym__object_body] = "_object_body",
  [sym_pair] = "pair",
  [sym_array] = "array",
  [sym_string] = "string",
  [sym__single_quoted_string] = "_single_quoted_string",
  [sym__double_quoted_string] = "_double_quoted_string",
  [aux_sym__single_string_content] = "_single_string_content",
  [aux_sym__double_string_content] = "_double_string_content",
  [sym__sign] = "_sign",
  [sym_number] = "number",
  [aux_sym__object_body_repeat1] = "_object_body_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__object_body_token1] = aux_sym__object_body_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_identifier] = sym_identifier,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_double_string_content] = sym_double_string_content,
  [sym_single_string_content] = sym_double_string_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_Infinity] = anon_sym_Infinity,
  [anon_sym_NaN] = anon_sym_NaN,
  [sym__number] = sym__number,
  [sym__hexadecimal_number] = sym__hexadecimal_number,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_null] = sym_null,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym__value] = sym__value,
  [sym_object] = sym_object,
  [sym__object_body] = sym__object_body,
  [sym_pair] = sym_pair,
  [sym_array] = sym_array,
  [sym_string] = sym_string,
  [sym__single_quoted_string] = sym__single_quoted_string,
  [sym__double_quoted_string] = sym__double_quoted_string,
  [aux_sym__single_string_content] = aux_sym__single_string_content,
  [aux_sym__double_string_content] = aux_sym__double_string_content,
  [sym__sign] = sym__sign,
  [sym_number] = sym_number,
  [aux_sym__object_body_repeat1] = aux_sym__object_body_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__object_body_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_double_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_single_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Infinity] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NaN] = {
    .visible = true,
    .named = false,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym__hexadecimal_number] = {
    .visible = false,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym__object_body] = {
    .visible = false,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__single_quoted_string] = {
    .visible = false,
    .named = true,
  },
  [sym__double_quoted_string] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__single_string_content] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__double_string_content] = {
    .visible = false,
    .named = false,
  },
  [sym__sign] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__object_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 12,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 25,
  [32] = 14,
  [33] = 33,
  [34] = 33,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 28,
  [40] = 40,
  [41] = 41,
  [42] = 27,
  [43] = 30,
  [44] = 11,
  [45] = 29,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym__value,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym__value] = {.index = 0, .length = 7},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_array,
    sym_false,
    sym_null,
    sym_number,
    sym_object,
    sym_string,
    sym_true,
};

static const TSCharacterRange sym_identifier_character_set_1[] = {
  {'$', '$'}, {'A', 'Z'}, {'\\', '\\'}, {'_', '_'}, {'a', 'z'}, {0x7f, 0x9f}, {0xa1, 0x167f}, {0x1681, 0x1fff},
  {0x200c, 0x2027}, {0x202a, 0x202e}, {0x2030, 0x205e}, {0x2061, 0x2fff}, {0x3001, 0xfefe}, {0xff00, 0x10ffff},
};

static const TSCharacterRange sym_identifier_character_set_2[] = {
  {'$', '$'}, {'0', '9'}, {'A', 'Z'}, {'\\', '\\'}, {'_', '_'}, {'a', 'z'}, {0x7f, 0x9f}, {0xa1, 0x167f},
  {0x1681, 0x1fff}, {0x200c, 0x2027}, {0x202a, 0x202e}, {0x2030, 0x205e}, {0x2061, 0x2fff}, {0x3001, 0xfefe}, {0xff00, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(44);
      ADVANCE_MAP(
        '"', 55,
        '\'', 54,
        '+', 68,
        '-', 67,
        '.', 34,
        '/', 8,
        '0', 71,
        ':', 49,
        '=', 50,
        'I', 22,
        'N', 12,
        '[', 51,
        '\\', 5,
        ']', 52,
        'f', 13,
        'n', 29,
        't', 24,
        '{', 45,
        '}', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(42);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(66);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == ',') ADVANCE(47);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == ']') ADVANCE(52);
      if (lookahead == '}') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(6);
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead == '\\') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(7);
      if (lookahead == '\'') ADVANCE(54);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead == '\\') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '\r', 1,
        '\n', 66,
        '"', 66,
        '\'', 66,
        '/', 66,
        '\\', 66,
        'b', 66,
        'f', 66,
        'n', 66,
        'r', 66,
        't', 66,
        'u', 66,
      );
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '/') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == '\'') ADVANCE(54);
      if (lookahead == '/') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(10);
      if (lookahead == '/') ADVANCE(80);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(79);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(9);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == 'N') ADVANCE(70);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(78);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 30:
      if (lookahead == 'y') ADVANCE(69);
      END_STATE();
    case 31:
      if (lookahead == '{') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == '}') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 33:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(35);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(75);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 40:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 41:
      if (eof) ADVANCE(44);
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == ',') ADVANCE(47);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == ']') ADVANCE(52);
      if (lookahead == '}') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(41);
      END_STATE();
    case 42:
      if (eof) ADVANCE(44);
      ADVANCE_MAP(
        '"', 55,
        '\'', 54,
        '+', 68,
        '-', 67,
        '.', 34,
        '/', 8,
        '0', 71,
        ':', 49,
        '=', 50,
        'I', 22,
        'N', 12,
        '[', 51,
        ']', 52,
        'f', 13,
        'n', 29,
        't', 24,
        '{', 45,
        '}', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(42);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 43:
      if (eof) ADVANCE(44);
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '\'') ADVANCE(54);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '\\') ADVANCE(28);
      if (lookahead == '}') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(43);
      if (set_contains(sym_identifier_character_set_1, 14, lookahead)) ADVANCE(53);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__object_body_token1);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym__object_body_token1);
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == ',') ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\\') ADVANCE(28);
      if (set_contains(sym_identifier_character_set_2, 15, lookahead)) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_double_string_content);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead == '/') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(60);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_double_string_content);
      if (lookahead == '*') ADVANCE(57);
      if (lookahead == '/') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_double_string_content);
      if (lookahead == '*') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_double_string_content);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_double_string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_single_string_content);
      if (lookahead == '*') ADVANCE(63);
      if (lookahead == '/') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(65);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_single_string_content);
      if (lookahead == '*') ADVANCE(62);
      if (lookahead == '/') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_single_string_content);
      if (lookahead == '*') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_single_string_content);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_single_string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_Infinity);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_NaN);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__number);
      if (lookahead == '.') ADVANCE(73);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(33);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(36);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__number);
      if (lookahead == '.') ADVANCE(73);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__hexadecimal_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 43},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 43},
  [8] = {.lex_state = 43},
  [9] = {.lex_state = 43},
  [10] = {.lex_state = 43},
  [11] = {.lex_state = 41},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 41},
  [16] = {.lex_state = 41},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 41},
  [21] = {.lex_state = 41},
  [22] = {.lex_state = 41},
  [23] = {.lex_state = 41},
  [24] = {.lex_state = 41},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 41},
  [27] = {.lex_state = 41},
  [28] = {.lex_state = 41},
  [29] = {.lex_state = 41},
  [30] = {.lex_state = 41},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 41},
  [36] = {.lex_state = 41},
  [37] = {.lex_state = 41},
  [38] = {.lex_state = 41},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 41},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 41},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 41},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_Infinity] = ACTIONS(1),
    [anon_sym_NaN] = ACTIONS(1),
    [sym__number] = ACTIONS(1),
    [sym__hexadecimal_number] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_document] = STATE(47),
    [sym__object_body] = STATE(50),
    [sym_pair] = STATE(36),
    [sym_string] = STATE(40),
    [sym__single_quoted_string] = STATE(44),
    [sym__double_quoted_string] = STATE(44),
    [aux_sym__object_body_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__value] = STATE(38),
    [sym_object] = STATE(16),
    [sym_array] = STATE(16),
    [sym_string] = STATE(16),
    [sym__single_quoted_string] = STATE(11),
    [sym__double_quoted_string] = STATE(11),
    [sym__sign] = STATE(17),
    [sym_number] = STATE(16),
    [aux_sym_array_repeat1] = STATE(4),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_Infinity] = ACTIONS(25),
    [anon_sym_NaN] = ACTIONS(25),
    [sym__number] = ACTIONS(27),
    [sym__hexadecimal_number] = ACTIONS(25),
    [sym_true] = ACTIONS(29),
    [sym_false] = ACTIONS(29),
    [sym_null] = ACTIONS(29),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__value] = STATE(41),
    [sym_object] = STATE(16),
    [sym_array] = STATE(16),
    [sym_string] = STATE(16),
    [sym__single_quoted_string] = STATE(11),
    [sym__double_quoted_string] = STATE(11),
    [sym__sign] = STATE(17),
    [sym_number] = STATE(16),
    [aux_sym_array_repeat1] = STATE(2),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(31),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_Infinity] = ACTIONS(25),
    [anon_sym_NaN] = ACTIONS(25),
    [sym__number] = ACTIONS(27),
    [sym__hexadecimal_number] = ACTIONS(25),
    [sym_true] = ACTIONS(29),
    [sym_false] = ACTIONS(29),
    [sym_null] = ACTIONS(29),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__value] = STATE(46),
    [sym_object] = STATE(16),
    [sym_array] = STATE(16),
    [sym_string] = STATE(16),
    [sym__single_quoted_string] = STATE(11),
    [sym__double_quoted_string] = STATE(11),
    [sym__sign] = STATE(17),
    [sym_number] = STATE(16),
    [aux_sym_array_repeat1] = STATE(4),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(36),
    [anon_sym_RBRACK] = ACTIONS(39),
    [anon_sym_SQUOTE] = ACTIONS(41),
    [anon_sym_DQUOTE] = ACTIONS(44),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_PLUS] = ACTIONS(47),
    [anon_sym_Infinity] = ACTIONS(50),
    [anon_sym_NaN] = ACTIONS(50),
    [sym__number] = ACTIONS(53),
    [sym__hexadecimal_number] = ACTIONS(50),
    [sym_true] = ACTIONS(56),
    [sym_false] = ACTIONS(56),
    [sym_null] = ACTIONS(56),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__value] = STATE(35),
    [sym_object] = STATE(16),
    [sym_array] = STATE(16),
    [sym_string] = STATE(16),
    [sym__single_quoted_string] = STATE(11),
    [sym__double_quoted_string] = STATE(11),
    [sym__sign] = STATE(17),
    [sym_number] = STATE(16),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_Infinity] = ACTIONS(25),
    [anon_sym_NaN] = ACTIONS(25),
    [sym__number] = ACTIONS(27),
    [sym__hexadecimal_number] = ACTIONS(25),
    [sym_true] = ACTIONS(29),
    [sym_false] = ACTIONS(29),
    [sym_null] = ACTIONS(29),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym__number,
    ACTIONS(39), 13,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_Infinity,
      anon_sym_NaN,
      sym__hexadecimal_number,
      sym_true,
      sym_false,
      sym_null,
  [22] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(69), 1,
      anon_sym_DQUOTE,
    STATE(7), 1,
      aux_sym__object_body_repeat1,
    STATE(40), 1,
      sym_string,
    STATE(48), 1,
      sym_pair,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(44), 2,
      sym__single_quoted_string,
      sym__double_quoted_string,
  [52] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      aux_sym__object_body_repeat1,
    STATE(36), 1,
      sym_pair,
    STATE(40), 1,
      sym_string,
    STATE(49), 1,
      sym__object_body,
    STATE(44), 2,
      sym__single_quoted_string,
      sym__double_quoted_string,
  [84] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    STATE(7), 1,
      aux_sym__object_body_repeat1,
    STATE(37), 1,
      sym_pair,
    STATE(40), 1,
      sym_string,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(44), 2,
      sym__single_quoted_string,
      sym__double_quoted_string,
  [114] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [125] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
    ACTIONS(78), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [137] = 4,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    STATE(19), 1,
      aux_sym__double_string_content,
    ACTIONS(84), 2,
      sym_double_string_content,
      sym_escape_sequence,
  [151] = 4,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    STATE(19), 1,
      aux_sym__double_string_content,
    ACTIONS(84), 2,
      sym_double_string_content,
      sym_escape_sequence,
  [165] = 4,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_DQUOTE,
    STATE(13), 1,
      aux_sym__double_string_content,
    ACTIONS(90), 2,
      sym_double_string_content,
      sym_escape_sequence,
  [179] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
    ACTIONS(94), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [191] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
    ACTIONS(98), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [203] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      sym__number,
    ACTIONS(100), 3,
      anon_sym_Infinity,
      anon_sym_NaN,
      sym__hexadecimal_number,
  [215] = 4,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_SQUOTE,
    STATE(18), 1,
      aux_sym__single_string_content,
    ACTIONS(106), 2,
      sym_single_string_content,
      sym_escape_sequence,
  [229] = 4,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_DQUOTE,
    STATE(19), 1,
      aux_sym__double_string_content,
    ACTIONS(111), 2,
      sym_double_string_content,
      sym_escape_sequence,
  [243] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(114), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
    ACTIONS(116), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [255] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(118), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
    ACTIONS(120), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [267] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(122), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
    ACTIONS(124), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [279] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
    ACTIONS(128), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [291] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(130), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
    ACTIONS(132), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [303] = 4,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_SQUOTE,
    STATE(34), 1,
      aux_sym__single_string_content,
    ACTIONS(136), 2,
      sym_single_string_content,
      sym_escape_sequence,
  [317] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(138), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
    ACTIONS(140), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [329] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(142), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
    ACTIONS(144), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [341] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(146), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
    ACTIONS(148), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [353] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(150), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
    ACTIONS(152), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [365] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(154), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
    ACTIONS(156), 2,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [377] = 4,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      aux_sym__single_string_content,
    ACTIONS(160), 2,
      sym_single_string_content,
      sym_escape_sequence,
  [391] = 4,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      aux_sym__double_string_content,
    ACTIONS(164), 2,
      sym_double_string_content,
      sym_escape_sequence,
  [405] = 4,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_SQUOTE,
    STATE(18), 1,
      aux_sym__single_string_content,
    ACTIONS(168), 2,
      sym_single_string_content,
      sym_escape_sequence,
  [419] = 4,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_SQUOTE,
    STATE(18), 1,
      aux_sym__single_string_content,
    ACTIONS(168), 2,
      sym_single_string_content,
      sym_escape_sequence,
  [433] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
    ACTIONS(172), 2,
      ts_builtin_sym_end,
      aux_sym__object_body_token1,
  [444] = 4,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    ACTIONS(178), 1,
      aux_sym__object_body_token1,
  [457] = 4,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(178), 1,
      aux_sym__object_body_token1,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
  [470] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(184), 1,
      aux_sym__object_body_token1,
    ACTIONS(186), 1,
      anon_sym_RBRACK,
  [480] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [488] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [496] = 3,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(184), 1,
      aux_sym__object_body_token1,
    ACTIONS(190), 1,
      anon_sym_RBRACK,
  [506] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [514] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [522] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [530] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [538] = 2,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(184), 1,
      aux_sym__object_body_token1,
  [545] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
  [552] = 2,
    ACTIONS(80), 1,
      sym_comment,
    ACTIONS(178), 1,
      aux_sym__object_body_token1,
  [559] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
  [566] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 22,
  [SMALL_STATE(8)] = 52,
  [SMALL_STATE(9)] = 84,
  [SMALL_STATE(10)] = 114,
  [SMALL_STATE(11)] = 125,
  [SMALL_STATE(12)] = 137,
  [SMALL_STATE(13)] = 151,
  [SMALL_STATE(14)] = 165,
  [SMALL_STATE(15)] = 179,
  [SMALL_STATE(16)] = 191,
  [SMALL_STATE(17)] = 203,
  [SMALL_STATE(18)] = 215,
  [SMALL_STATE(19)] = 229,
  [SMALL_STATE(20)] = 243,
  [SMALL_STATE(21)] = 255,
  [SMALL_STATE(22)] = 267,
  [SMALL_STATE(23)] = 279,
  [SMALL_STATE(24)] = 291,
  [SMALL_STATE(25)] = 303,
  [SMALL_STATE(26)] = 317,
  [SMALL_STATE(27)] = 329,
  [SMALL_STATE(28)] = 341,
  [SMALL_STATE(29)] = 353,
  [SMALL_STATE(30)] = 365,
  [SMALL_STATE(31)] = 377,
  [SMALL_STATE(32)] = 391,
  [SMALL_STATE(33)] = 405,
  [SMALL_STATE(34)] = 419,
  [SMALL_STATE(35)] = 433,
  [SMALL_STATE(36)] = 444,
  [SMALL_STATE(37)] = 457,
  [SMALL_STATE(38)] = 470,
  [SMALL_STATE(39)] = 480,
  [SMALL_STATE(40)] = 488,
  [SMALL_STATE(41)] = 496,
  [SMALL_STATE(42)] = 506,
  [SMALL_STATE(43)] = 514,
  [SMALL_STATE(44)] = 522,
  [SMALL_STATE(45)] = 530,
  [SMALL_STATE(46)] = 538,
  [SMALL_STATE(47)] = 545,
  [SMALL_STATE(48)] = 552,
  [SMALL_STATE(49)] = 559,
  [SMALL_STATE(50)] = 566,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__object_body_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__object_body_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__object_body_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__object_body_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__object_body, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__single_string_content, 2, 0, 0),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__single_string_content, 2, 0, 0), SHIFT_REPEAT(18),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__double_string_content, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__double_string_content, 2, 0, 0), SHIFT_REPEAT(19),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__single_quoted_string, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__single_quoted_string, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__double_quoted_string, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__double_quoted_string, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__single_quoted_string, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__single_quoted_string, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__double_quoted_string, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__double_quoted_string, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 1),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 3, 0, 1),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__object_body, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__object_body, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__object_body, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [192] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sjson(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "sjson",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 24,
      .patch_version = 8,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
